### ISSUE TITLE
error chrome

### ISSUE THREAD

**Issue by ikkehman** [AgiMaulana/Instagram-Comments-Scraper#9]
pas di running selalu error

> Traceback (most recent call last):
  File "scraper.py", line 5, in <module>
    driver = webdriver.Chrome()
  File "/root/Instagram-Comments-Scraper/.venv/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/root/Instagram-Comments-Scraper/.venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/Instagram-Comments-Scraper/.venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/Instagram-Comments-Scraper/.venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/Instagram-Comments-Scraper/.venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

padahal versi driver sama chrome udah sama (90.0.4430.93-0ubuntu0.18.04.1)

**Comment by AgiMaulana** [comment]
@ikkehman Hi, are you using Chromium browser instead of Google Chrome? Chromium and Google Chrome has a little bit different I though
